# Generated by Django 6.0.2 on 2026-07-30 11:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='decision',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('challenged', 'Challenged'), ('blocked', 'Blocked')], default='allowed', max_length=20),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='matched_rule',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='IPRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_or_cidr', models.CharField(help_text='Single IP or CIDR notation', max_length=45)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ip_rules', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_rules', to='vericlick.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
