# Generated by Django 6.0.2 on 2026-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0002_clicklog_decision_clicklog_matched_rule_iprule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='last_domain_scan_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
