# Generated by Django 6.0.2 on 2026-08-01 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0003_workspace_last_domain_scan_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_url', models.URLField(max_length=2048)),
                ('referrer', models.URLField(blank=True, default='', max_length=2048)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('engagement', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_events', to='vericlick.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
