# Generated by Django 6.0.2 on 2026-08-01 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0004_trackerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='tracker_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
