# Generated by Django 6.0.2 on 2026-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0005_workspace_tracker_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='domainregistry',
            name='verified',
            field=models.BooleanField(default=False, help_text='True once a health check confirms the domain resolves (DNS ownership check).'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='safe_destination',
            field=models.URLField(blank=True, default='', help_text='Where suspicious traffic is sent instead of the real destination.', max_length=2048),
        ),
    ]
