# Generated by Django 6.0.2 on 2026-08-03 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0006_clicklog_city_clicklog_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistry',
            name='verification_token',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='Random token used to prove DNS ownership via a TXT record.', max_length=64),
        ),
        migrations.AlterField(
            model_name='domainregistry',
            name='verified',
            field=models.BooleanField(default=False, help_text='True only after the owner proves control by adding the TXT verification record. Distinct from health_status, which only confirms the domain resolves.'),
        ),
    ]
