# Generated by Django 6.0.2 on 2026-08-05 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0007_domainregistry_verification_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='e.g. basic, plus, pro', unique=True)),
                ('name', models.CharField(help_text='Display name, e.g. Basic', max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly price in USD.', max_digits=8)),
                ('domain_limit', models.PositiveIntegerField(help_text='How many domains a workspace on this plan may register.')),
                ('features', models.JSONField(blank=True, default=list, help_text='Extra bullet points shown on the pricing page.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans are hidden from the pricing endpoint.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='Percentage off the monthly price, 1-100 (e.g. 20).')),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Total number of times this code can be used. Blank = unlimited.', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry. Blank = never expires.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discount_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The paid plan this workspace is on. Null means free/beta (no paid plan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='vericlick.plan'),
        ),
    ]
