# Generated by Django 6.0.2 on 2026-08-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0009_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('key', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('beta_free_mode', models.BooleanField(default=True, help_text='While True (beta), every feature is free: plan limits are not enforced and workspaces get unlimited domains. Set False to start enforcing the paid plan domain limits.')),
                ('signups_open', models.BooleanField(default=True, help_text='While True, new accounts (register and Google sign-in) are allowed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
    ]
