# Generated by Django 6.0.2 on 2026-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0011_seed_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistry',
            name='points_to_server',
            field=models.BooleanField(default=False, help_text='True when the domain does more than resolve — its DNS points at this server (A/CNAME to the VeriClick IP). A domain must resolve, be verified, and point at the server before tracking links can live on it.'),
        ),
    ]
