# Generated by Django 6.0.2 on 2026-08-10
import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0012_domainregistry_points_to_server'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='bachs_product_id',
            field=models.CharField(blank=True, default='', help_text='The Bachs recurring product ID (prod_...) this plan is sold as. Create a matching recurring product in Bachs, then paste its ID here — upgrading to this plan routes through that product\'s checkout.', max_length=64),
        ),
        migrations.CreateModel(
            name='CheckoutIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkout_id', models.CharField(blank=True, db_index=True, default='', help_text='Bachs checkout ID (chk_...). Empty until Bachs answers.', max_length=100)),
                ('charge_id', models.CharField(blank=True, default='', help_text='Bachs charge ID (chr_...), if provided on the webhook.', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('failed', 'Failed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_intents', to='vericlick.plan')),
                ('user', models.ForeignKey(blank=True, help_text='The account that started the checkout (for the upgrade email).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_intents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_intents', to='vericlick.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]