# Generated by Django 6.0.2 on 2026-08-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0015_siteconfig_remove_beta_free_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistry',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete marker. A verified domain keeps occupying its plan slot until the current period ends even after removal; unverified domains never count and can be removed and re-added freely.', null=True),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete marker. A link on a verified domain keeps occupying its plan slot until the current period ends even after removal.', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='plan_started_at',
            field=models.DateTimeField(blank=True, help_text='When the current paid-plan period began. Used to decide when soft-deleted domains/links stop counting toward the plan limits: a removed verified domain (or a link on one) keeps its slot until the current period ends. Set automatically the first time a plan is assigned.', null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The paid plan this workspace is on. Null means the free tier (no paid plan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='vericlick.plan'),
        ),
    ]
