# Generated by Django 6.0.2 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0016_domain_link_soft_delete_and_period'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['-created_at'], name='clicklog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['link', '-created_at'], name='clicklog_link_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clicklog',
            index=models.Index(fields=['link', 'decision', '-created_at'], name='clicklog_link_dec_created_idx'),
        ),
    ]