# Generated by Django 6.0.2 on 2026-08-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0017_clicklog_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAsnRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.CharField(help_text='First IP of the range (text form)', max_length=45)),
                ('end_ip', models.CharField(help_text='Last IP of the range (text form)', max_length=45)),
                ('asn', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=4)),
                ('org', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['start_ip'],
            },
        ),
        migrations.AddField(
            model_name='iprule',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', help_text='How the rule was created. Auto rules are generated by the reputation system when an IP trips the traffic checks repeatedly; they expire on their own and can be deleted like manual rules.', max_length=10),
        ),
        migrations.AddField(
            model_name='workspace',
            name='auto_reputation_enabled',
            field=models.BooleanField(default=True, help_text='When on, IPs that keep tripping the traffic checks (bot/rate/datacenter) are automatically denied for 24h so repeated offenders stay blocked, and traffic from hosting/datacenter/VPN networks is diverted to the safe destination. Allow rules still always win.'),
        ),
    ]
