# Generated by Django 6.0.2 on 2026-08-12 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0018_ipasnrange_iprule_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutintent',
            name='billing_mode',
            field=models.CharField(choices=[('subscription', 'Recurring card subscription'), ('period', 'One-time period (any payment channel)')], default='subscription', help_text='subscription = recurring card charge; period = one-time payment covering a billing period.', max_length=16),
        ),
        migrations.AddField(
            model_name='checkoutintent',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='Payment channel actually used (card, mobile_money, crypto, bank_transfer), when the webhook reports it.', max_length=24),
        ),
        migrations.AddField(
            model_name='workspace',
            name='plan_billing_mode',
            field=models.CharField(choices=[('subscription', 'Subscription (card, auto-renews)'), ('period', 'One-time period (manual renew)')], default='subscription', help_text='How this plan is paid: subscription = card monthly auto-renew; period = a one-time payment covering a billing period (bank transfer / crypto / mobile money), renewed manually.', max_length=16),
        ),
        migrations.AddField(
            model_name='workspace',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the current billing period ends. Null on card subscriptions. Set on one-time "period" payments; once passed, the workspace is treated as having no active plan until it pays again.', null=True),
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('trial_started', 'Trial started'), ('plan_purchased', 'Plan purchased'), ('plan_renewed', 'Plan renewed'), ('plan_period_paid', 'One-time period paid'), ('plan_expiring', 'Period expiring soon'), ('plan_expired', 'Billing period ended'), ('payment_failed', 'Payment failed'), ('refunded', 'Refunded')], max_length=24)),
                ('plan_name', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount charged (USD unless currency says otherwise).', max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('charge_id', models.CharField(blank=True, db_index=True, default='', help_text='Bachs charge ID (chr_...), when known.', max_length=100)),
                ('checkout_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra snapshot info (mode, channel, expiry, etc.).')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='vericlick.plan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='vericlick.workspace')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
