# Generated by Django 6.0.2 on 2026-08-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0019_checkoutintent_billing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistry',
            name='health_detail',
            field=models.JSONField(blank=True, default=dict, help_text='Last DNS diagnosis report from the health scan: one plain-language finding per layer (nameservers, apex, TXT, tracking host) with fix steps. Rendered in the app and in the admin so a "degraded" domain explains itself.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='bachs_payment_link',
            field=models.URLField(blank=True, default='', help_text='Optional Bachs payment link (https://checkout.bachs.io/pay/pl_...) for this product, for reference / manual invoicing. Not used by the API — checkouts are created per customer so attributions and auto-granting work.', max_length=512),
        ),
    ]
