# Generated by Django 6.0.2 on 2026-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0020_domain_health_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='bachs_ot_product_id',
            field=models.CharField(blank=True, default='', help_text='The Bachs ONE-TIME product ID (prod_...) used when a customer buys a 30-day "period" of this plan. One-time checkouts are the only ones that can show card / crypto / bank transfer / mobile money. Leave blank to fall back to bachs_product_id.', max_length=64),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='kind',
            field=models.CharField(choices=[('trial_started', 'Trial started'), ('plan_purchased', 'Plan purchased'), ('plan_renewed', 'Plan renewed'), ('plan_period_paid', 'One-time period paid'), ('plan_expiring', 'Period expiring soon'), ('plan_expired', 'Billing period ended'), ('plan_suspended', 'Access suspended'), ('payment_failed', 'Payment failed'), ('refunded', 'Refunded')], max_length=24),
        ),
    ]
