# Generated by Django 6.0.2 on 2026-08-14 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_verified(apps, schema_editor):
    # Instant domain authorization (v2.0.0): a domain becomes "authorized"
    # (verified) the moment it is registered — ownership is proven by the
    # fact that the user added it from their own account. Existing domains
    # all keep their verified status so nothing regresses on deploy.
    DomainRegistry = apps.get_model('vericlick', 'DomainRegistry')
    DomainRegistry.objects.filter(verified=False).update(verified=True)


def unbackfill_verified(apps, schema_editor):
    # Reversible for completeness; there is no way to know which rows were
    # originally verified, so this is a no-op.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0021_plan_bachs_ot_product_id_alter_billingevent_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clicklog',
            name='browser',
            field=models.CharField(blank=True, default='', help_text='Browser family from the user agent (Chrome, Safari, ...).', max_length=64),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code, so country rules and country breakdowns can match precisely.', max_length=2),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='device_class',
            field=models.CharField(blank=True, default='', help_text='Normalized device class from the user agent: mobile, tablet, desktop, bot or other.', max_length=20),
        ),
        migrations.AddField(
            model_name='clicklog',
            name='os_family',
            field=models.CharField(blank=True, default='', help_text='Normalized OS family from the user agent (Windows, macOS, Android, iOS, ...).', max_length=64),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='Whether the shield judged this pageview as bot/automated traffic.'),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='reason',
            field=models.CharField(blank=True, default='', help_text='Short reason code behind the verdict (e.g. suspicious UA, country deny).', max_length=100),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='verdict',
            field=models.CharField(blank=True, default='', help_text='Shield verdict for this pageview: "allowed" or "blocked". Empty = not evaluated.', max_length=20),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='allowed_countries',
            field=models.JSONField(blank=True, default=list, help_text='ISO 3166-1 alpha-2 country codes allowed to open this link. Empty = all.'),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='allowed_devices',
            field=models.JSONField(blank=True, default=list, help_text='Device classes allowed to open this link (mobile, tablet, desktop). Empty = all.'),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='bot_action',
            field=models.CharField(choices=[('safe', 'Send to safe page'), ('404', 'Serve a 404'), ('block', 'Block the request')], default='safe', help_text='How this link handles detected bots: divert to the safe page, serve a 404, or hard-block.', max_length=10),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='safe_url',
            field=models.URLField(blank=True, default='', help_text='Optional per-link destination for bot/suspicious traffic. Empty = use the workspace safe destination.', max_length=2048),
        ),
        migrations.CreateModel(
            name='CountryRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code (e.g. US, NG, CN).', max_length=2)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', help_text='How the rule was created. Auto rules are generated from the dashboard one-click block buttons; they can be deleted like manual rules.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_country_rules', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_rules', to='vericlick.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_device_classes', models.JSONField(blank=True, default=list, help_text='Device classes allowed to open links (mobile, tablet, desktop). Empty = all.')),
                ('blocked_os_families', models.JSONField(blank=True, default=list, help_text='OS families blocked from opening links (Windows, Android, ...). Empty = none.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_policy', to='vericlick.workspace')),
            ],
            options={
                'verbose_name_plural': 'Device policies',
            },
        ),
        migrations.RunPython(backfill_verified, unbackfill_verified),
    ]
