# Generated by Django 6.0.2 on 2026-08-14

from django.db import migrations


def unverify_removed_domains(apps, schema_editor):
    # 0022's backfill set verified=True on EVERY unverified domain, including
    # ones the user had already soft-deleted before instant authorization
    # existed. A deleted domain that was never verified must not become
    # "authorized" retroactively: it was removed under the old TXT model, so
    # it neither shows in the app nor counts toward the plan slot until the
    # period ends. This reverts that over-backfill for soft-deleted rows only.
    DomainRegistry = apps.get_model('vericlick', 'DomainRegistry')
    DomainRegistry.objects.filter(removed_at__isnull=False).update(verified=False)


def reverify_removed_domains(apps, schema_editor):
    # Reversible for completeness. Restores the state 0022 produced for
    # soft-deleted domains (all verified). No-op is fine — we don't need to
    # undo this in practice.
    DomainRegistry = apps.get_model('vericlick', 'DomainRegistry')
    DomainRegistry.objects.filter(removed_at__isnull=False).update(verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0022_traffic_rules_and_instant_authorize'),
    ]

    operations = [
        migrations.RunPython(unverify_removed_domains, reverify_removed_domains),
    ]
