# Generated by Django 6.0.2 on 2026-08-18 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0025_trackerevent_canvas_hash_trackerevent_ja4_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection_mode', models.CharField(choices=[('strict', 'Strict — block all detected bots'), ('balanced', 'Balanced — block obvious bots, challenge suspicious'), ('monitor', "Monitor only — log but don't block")], default='balanced', max_length=16)),
                ('bot_action', models.CharField(choices=[('block', 'Show block page'), ('honeypot', 'Redirect to honeypot page'), ('log', 'Log only, let through')], default='block', max_length=10)),
                ('protected_paths', models.JSONField(blank=True, default=list, help_text='Paths to protect (empty = all pages). E.g. ["/checkout", "/pricing"].')),
                ('blocked_paths', models.JSONField(blank=True, default=list, help_text='Paths to never protect (e.g. ["/admin", "/api"]).')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=100, help_text='Max visits per IP per hour before triggering rate limit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shield configuration',
                'verbose_name_plural': 'Shield configurations',
            },
        ),
        migrations.RemoveField(
            model_name='abusereport',
            name='link',
        ),
        migrations.RemoveField(
            model_name='abusereport',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='abusereport',
            name='workspace',
        ),
        migrations.RemoveIndex(
            model_name='clicklog',
            name='clicklog_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='clicklog',
            name='clicklog_link_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='clicklog',
            name='clicklog_link_dec_created_idx',
        ),
        migrations.RemoveField(
            model_name='destinationchangelog',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='destinationchangelog',
            name='link',
        ),
        migrations.RemoveField(
            model_name='domainregistry',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='trackinglink',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='trackinglink',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='last_domain_scan_at',
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='country',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='device_class',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='os_family',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trackerevent',
            name='region',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='shieldconfig',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shield_config', to='vericlick.workspace'),
        ),
        migrations.DeleteModel(
            name='AbuseReport',
        ),
        migrations.RemoveField(
            model_name='clicklog',
            name='link',
        ),
        migrations.DeleteModel(
            name='DestinationChangeLog',
        ),
        migrations.DeleteModel(
            name='DomainRegistry',
        ),
        migrations.DeleteModel(
            name='ClickLog',
        ),
        migrations.DeleteModel(
            name='TrackingLink',
        ),
    ]
