# Generated by Django 6.0.2 on 2026-08-18 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0026_trackerevent_location_device_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Registered domain (e.g. example.com).', max_length=253)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag — removed domains keep their slot until period ends.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='vericlick.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('workspace', 'domain')},
            },
        ),
    ]
