# Generated by Django 6.0.2 on 2026-08-19 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0027_add_domainregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainregistry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
