# Generated by Django 6.0.2 on 2026-08-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0028_domainregistry_add_uuid_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerevent',
            name='domain',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Domain extracted from page_url (e.g. example.com). Used for per-domain dashboard filtering.', max_length=253),
        ),
    ]
