# Generated by Django 6.0.2 on 2026-08-19 13:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0029_trackerevent_add_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainregistry',
            name='health_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('unhealthy', 'Unreachable')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='domainregistry',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainregistry',
            name='purpose',
            field=models.CharField(choices=[('protection', 'Bot Protection'), ('redirect', 'Smart Redirect')], default='protection', max_length=10),
        ),
        migrations.AddField(
            model_name='domainregistry',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('html_meta', 'HTML Meta Tag'), ('dns_txt', 'DNS TXT Record')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='domainregistry',
            name='verification_token',
            field=models.CharField(blank=True, default='', help_text='Auto-generated challenge token for domain verification.', max_length=64),
        ),
        migrations.AddField(
            model_name='domainregistry',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domainregistry',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InstallToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_prefix', models.CharField(help_text='First chars for display.', max_length=12)),
                ('label', models.CharField(default='Primary', max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_tokens', to='vericlick.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
