# Generated by Django 6.0.2 on 2026-08-19 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0030_add_domain_verification_and_install_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeSyncCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='default', help_text='Human label for this edge node (e.g. "FlokiNET DE").', max_length=100)),
                ('api_secret', models.CharField(help_text='Shared secret. Shown once on creation.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_credentials', to='vericlick.workspace')),
            ],
            options={
                'db_table': 'edge_sync_credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedirectRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, default='', help_text='Short path on the redirect domain. Empty = root.', max_length=100)),
                ('destination_url', models.URLField(max_length=2048)),
                ('bot_action', models.CharField(choices=[('honeypot', 'Honeypot (trap bots)'), ('block', 'Block (403)')], default='honeypot', max_length=10)),
                ('fallback_url', models.URLField(blank=True, default='', help_text='Where to send suspected bots (empty = neutral fallback).', max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='After this time the redirect stops working. Auto-set to 7 days from creation.', null=True)),
                ('destination_safe', models.BooleanField(default=None, help_text='Last safety-check result for the destination URL.', null=True)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('abuse_status', models.CharField(choices=[('none', 'No abuse'), ('flagged', 'Flagged for review'), ('blocked', 'Blocked')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_routes', to='vericlick.domainregistry')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_routes', to='vericlick.workspace')),
            ],
            options={
                'db_table': 'redirect_routes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('domain', 'slug'), name='unique_active_route_per_domain_slug')],
            },
        ),
    ]
