# Generated by Django 6.0.2 on 2026-08-19 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0031_add_redirect_route_and_edge_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgesynccredential',
            name='api_secret',
        ),
        migrations.AddField(
            model_name='edgesynccredential',
            name='key_hash',
            field=models.CharField(default='', help_text='SHA-256 of the raw key. Never stored in plaintext.', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='edgesynccredential',
            name='key_prefix',
            field=models.CharField(default='', help_text='First 12 chars for display (ek_a1b2c3d4...).', max_length=12),
        ),
        migrations.AlterField(
            model_name='redirectroute',
            name='bot_action',
            field=models.CharField(choices=[('honeypot', 'Honeypot (trap bots)'), ('block', 'Block (404)'), ('neutral', 'Neutral (empty page)'), ('redirect', 'Redirect to fallback')], default='honeypot', max_length=10),
        ),
        migrations.AlterField(
            model_name='redirectroute',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_route', to='vericlick.domainregistry'),
        ),
        migrations.CreateModel(
            name='RedirectEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=253)),
                ('slug', models.CharField(blank=True, default='', max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('destination', models.URLField(max_length=2048)),
                ('verdict', models.CharField(max_length=20)),
                ('is_bot', models.BooleanField(default=False)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redirect_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vericlick.redirectroute')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_events', to='vericlick.workspace')),
            ],
            options={
                'db_table': 'redirect_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='redirect_ev_workspa_d809cb_idx'), models.Index(fields=['domain', 'created_at'], name='redirect_ev_domain_03bbd0_idx')],
            },
        ),
    ]
