# Generated by Django 6.0.2 on 2026-08-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0032_update_edge_sync_and_add_redirect_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shieldconfig',
            options={'verbose_name': 'Anti-bot configuration', 'verbose_name_plural': 'Anti-bot configurations'},
        ),
        migrations.AlterField(
            model_name='checkoutintent',
            name='billing_mode',
            field=models.CharField(choices=[('period', 'One-time period (crypto)')], default='period', help_text='One-time period payment (crypto), renewed manually.', max_length=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='domain_limit',
            field=models.PositiveIntegerField(default=1, help_text='How many domains a workspace on this plan may register.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, help_text='One-time price in USD (1-week access).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='trackerevent',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='Whether the anti-bot engine judged this pageview as bot/automated traffic.'),
        ),
        migrations.AlterField(
            model_name='trackerevent',
            name='verdict',
            field=models.CharField(blank=True, default='', help_text='Anti-bot verdict for this pageview: "allowed" or "blocked". Empty = not evaluated.', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='plan_billing_mode',
            field=models.CharField(choices=[('period', 'One-time period (manual renew)')], default='period', help_text='How this plan is paid: always a one-time payment covering a billing period (crypto), renewed manually.', max_length=16),
        ),
    ]
