# Generated by Django 6.0.2 on 2026-08-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0033_alter_shieldconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='onboarding_type',
            field=models.CharField(blank=True, choices=[('shield', 'Site Shield'), ('redirect', 'Smart Redirect')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='domain_limit',
            field=models.PositiveIntegerField(default=5, help_text='How many domains a workspace on this plan may register.'),
        ),
    ]
