# Generated by Django 6.0.2 on 2026-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0036_edgesynccredential_workspace_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectroute',
            name='use_shortlink',
            field=models.BooleanField(default=False, help_text='If true, this route is also available as vericlick.cc/<slug>.'),
        ),
        migrations.AlterField(
            model_name='domainregistry',
            name='purpose',
            field=models.CharField(choices=[('protection', 'Bot Protection'), ('redirect', 'Smart Redirect'), ('platform', 'Platform Shortlink')], default='protection', max_length=10),
        ),
    ]
