# Generated by Django 6.0.2 on 2026-08-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0037_shortlink_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectroute',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_routes', to='vericlick.domainregistry'),
        ),
    ]
