# Generated by Django 6.0.2 on 2026-08-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0038_update_plan_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='bachs_monthly_product_id',
            field=models.CharField(blank=True, default='', help_text='Bachs one-time product (prod_...) sold for a MONTHLY period — 30 days of access at the monthly price. Leave blank to disable monthly for this plan; the pricing page then shows it as unavailable rather than failing at checkout.', max_length=64, verbose_name='Bachs monthly product ID (one-time)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bachs_ot_product_id',
            field=models.CharField(blank=True, default='', help_text='Bachs one-time product (prod_...) sold for a WEEKLY period — 7 days of access at the weekly price. Bachs stores the price on the product, so weekly and monthly need separate products. Leave blank to disable weekly for this plan.', max_length=64, verbose_name='Bachs weekly product ID (one-time)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bachs_product_id',
            field=models.CharField(blank=True, default='', help_text='Unused. Subscriptions were removed — every purchase is a one-time period. Kept only so existing rows are not lost; set the weekly and monthly one-time product IDs instead.', max_length=64, verbose_name='Bachs recurring product ID (legacy)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time price for 30 days of access.', max_digits=8, verbose_name='Monthly price (USD)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='weekly_price',
            field=models.DecimalField(decimal_places=2, help_text='One-time price for 7 days of access.', max_digits=8, verbose_name='Weekly price (USD)'),
        ),
    ]
