# Generated by Django 6.0.2 on 2026-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0039_plan_admin_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainregistry',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivated domains do not count toward the plan limit. Deleting a domain removes the row outright and frees its slot immediately.'),
        ),
    ]
