# Generated by Django 6.0.2 on 2026-08-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0040_domainregistry_is_active_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='tour_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has seen the product tour. Stored per account, not in the browser, so signing in on a second device does not replay the pitch to someone who already sat through it.'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='onboarding_type',
            field=models.CharField(blank=True, choices=[('both', 'Shield + Redirect'), ('shield', 'Site Shield'), ('redirect', 'Smart Redirect')], help_text='Which setup path the workspace took. New signups use "both": one verified domain runs the anti-bot script and backs a redirect link. The single-purpose values are kept for workspaces onboarded earlier.', max_length=20, null=True),
        ),
    ]
