# Generated by Django 6.0.2 on 2026-08-21 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0041_onboarding_both_and_tour_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='notify_plan_reminders',
            field=models.BooleanField(default=True, help_text='Email the owner before and when a plan period lapses.'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='tracker_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public site key embedded in every protected page. Rotatable from Settings — rotating invalidates the old snippet, so the customer must paste the new one.'),
        ),
    ]
