# Generated by Django 6.0.2 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vericlick', '0038_shortlink_domain_fk'),
        ('vericlick', '0043_redirectevent_device_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='redirect_limit',
            field=models.PositiveIntegerField(default=2, help_text='Maximum active redirect routes (shortlinks + custom domains).'),
        ),
    ]
